### ISSUE TITLE
No puedo realizar grabaciones

### ISSUE THREAD

**Issue by moodleulpgc** [UNIMOODLE/moodle-mod_hybridteaching#102]
Necesito ayuda, no consigo realizar Grabaciones ni con BBB ni con Zoom. 

Si utilizo instancias de mod_bigbluebuttonbn, o mod_zoom con parámetros de configuración idénticos a los de los subplugins hybridteachvc_bbb o hybridteachvc_zoom, cuando como profesor inicio una reunión VC, veo y puedo usar un botón para grabar la reunión.

Pero si tengo instancias de mod_hybridteaching usando vc BBB o zoom, puedo iniciar la reunión, pero NO hay modo de grabar. Tampoco parace funcionar "grabar desde el inicio". 
Entiendo que debe ser cosa de configuración, pero las videconferencias se incian sin problemas. Y no veo settings que marcar en admin. 

¿Que se está escapando?

**Comment by tmas0** [comment]
Comprobado que ya funciona bien.
