### ISSUE TITLE
Control de correos/notificaciones desde organizardor de VC Teams

### ISSUE THREAD

**Issue by moodleulpgc** [UNIMOODLE/moodle-mod_hybridteaching#104]
Al generar una reunión usando vc_teams, en el modo "behalf", que incluye un usuario declarado en la configuración de la instancia del subplugisn (en este caso cvulpgc@ulpgc.es) resulta que TODOS los usuarios matriculados en el curso reciben un correo desde ese usuario: 

![Screenshot_20240214_141310](https://github.com/UNIMOODLE/moodle-mod_hybridteaching/assets/1895434/3e25fad5-8df5-4696-b128-d0a4545b7e18)

Esta es una de las cosas que este sistema debe poder controlar desde moodle (sin tocar explícitamente azure). Es decir la configuración de la instancia del subplugin (a lo mejor un tenant si, otro no; a lo mejor usado como "app" si, como "behafl" no)  debe existir un setting para que el admin indique si estos correos deben ser generados o NO deben serlo, al crear una videconferencia Teams. 
Es irrelevante si es una videconferencia programada o creada ad hoc. Debe ser uan propiedad de la instancia del subplugin. 

Si esto es aplicable a otros sistemas (meet, zoom), aplicar lo mismo. Controlado dede moodle.

**Comment by tmas0** [comment]
Buenas @mcalvoisyccom,

Siguiendo el hilo, no me queda claro si esto se pudo solucionar o no. Si es que no por falta del usuario que mencionas, lo intentamos revisar entre nosotros para poder solucionar el problema expuesto.

Un saludo

**Comment by mcalvoisyccom** [comment]
Hola @tmas0 ,
sí, se quedó ya solventado. Era por falta de licencias en el usuario, ya las tenemos disponibles.
Un saludo,
Marian Calvo.
