### ISSUE TITLE
Registro de asistencia por estudiante en aula: siempre incluso sin QR o clave

### ISSUE THREAD

**Issue by moodleulpgc** [UNIMOODLE/moodle-mod_hybridteaching#108]
Si se configura una instancia y se dejan en blanco, sin contenido, los datos de registro de asistencia (QR y/o contraseña) El estudiante NO puede entrar desde el aula

![Screenshot 2024-02-16 at 09-35-27 Editando Docencia híbrida moodle4unimoodle](https://github.com/UNIMOODLE/moodle-mod_hybridteaching/assets/1895434/214d9af4-519b-45b6-b886-7e08499c8f18)

Si NO se marca QR y NO se incluye un contenido en "contraseña de alumnos", entonces al estudiante  **SOLO** se le muestra el botón de unirse vía videoconferencia. NO hay mecanismo para poder "Registrar asistencia" desde el aula. 

El mecanismo (para el estudiante) para poder "Registrar asistencia" desde el aula, entrando vía web en al página view.php del plugin debe existir siempre. Lo que cambia es su contenido, solo un botón, o con un campo para  
O dicho de otra forma: si aparece el botón "unirse a la reunión" (para videoconferencias) también debe aparecer este otro mecanismo.

![Screenshot_20240216_094353](https://github.com/UNIMOODLE/moodle-mod_hybridteaching/assets/1895434/64f6dc4b-56f5-455d-bd70-5fad90d12fae)

Ejemplo  SIN campo para meter contraseña por el estudiante

**Comment by tmas0** [comment]
Comprobado que todo está corregido.

Un saludo
