### ISSUE TITLE
refactor: renderer y attendance/sessions_render

### ISSUE THREAD

**Issue by moodleulpgc** [UNIMOODLE/moodle-mod_hybridteaching#110]
En  hybridteaching/classes/output/ aparecen los archivos 
 - attendance_render.php
 - renderer.php
 - sessions_render.php

Pero si bien renderer.php efectivamente extiende un renderer
`class renderer extends plugin_renderer_base `

apenas tiene contenido, no hay metodos propios de mod_hybridteaching

En cambio los archivos xxxx_render NO son renderers, sino que extienden TABLAS 
`class sessions_render extends \table_sql implements dynamic_table `

Por lo tanto es confuso e inconsistente llamarlos _render y colocarlos en classes/output/
Es mejor colocarlos en otro sitio (directamente hybridteaching/classes/ o hybridteaching/classes/local)  y denominarlos 
attendance_table.php
sessions_table.php

Igual que se hace en, por ejemplo, el módulo mod_assign luego se visualiza en el renderer con un método
 render_attendance_table(attendance_table $table)

El método actual attendance_render->print_attendance_table() mezcla y combina obtención de estructuras de datos y lo que es propiamente su visualización. Justo lo que se trata de **evitar** con un renderer.

La idea es trabajar algo más explicitamente en attendance.php, 
 instanciar attendance_table $table, 
instanciar otros elementos necesarios 
```
        $attendancecontroller = new attendance_controller($this->hybridteaching);
        $sessionscontroller = new sessions_controller($this->hybridteaching);
```
y luego pasaralo todo al renderer. Al renderer, a los métodos renderer se le pasan estructuras con todos los datos necesarios. En los métodos del renderer NO debería llamarse a la BD ni a otras funciones que obtengan datos. 

Insisto, para tablas como estas flexible table, el mejor ejemplo a seguir en assign/gradingtable

**Comment by tmas0** [comment]
Comprobado.
