### ISSUE TITLE
Enlaces en iconos de acción con urls con exceso de parámetros

### ISSUE THREAD

**Issue by moodleulpgc** [UNIMOODLE/moodle-mod_hybridteaching#111]
En la páginas de Asistencia (no en otras) los iconos de acción, esos iconos tienen urls en exceso complejas sin necesidad aparente. LOs úticos parámetros deberían ser cmid, en ID de la fila (bien sesisonid si es asistencia a sesión o userid si es asistencia por usuario. Otros parámetros solo grupos y filtros, y orden de tabla.

Claramente  hay parámetros que sobran, 
userid. Si se necesita una userid, se toma de $USER->id en el script al que apunta esa url. 
Returnurl NO debe ser propiamente una url codificada sino un literal que identifica la página en la qu ese está  y a la que se vuelve  (sessionsattendance, usersattendance etc). En el script de destino eso de traduce en una url real. Parece incluso duplicado con otros parámetrso anteriores

https://localhost/moodle41ulpgc/mod/hybridteaching/action/attendance_action.php?sesskey=xabYkOhGKg&view=sessionattendance&sessionid=38&attid=38&h=2&id=21209&returnurl=https%3A%2F%2Flocalhost%2Fmoodle41ulpgc%2Fmod%2Fhybridteaching%2Fattendance.php%3Fid%3D21209%26amp%3Bview%3Dsessionattendance&userid=2&action=view

![Screenshot_20240216_200809](https://github.com/UNIMOODLE/moodle-mod_hybridteaching/assets/1895434/519c75e7-a73c-4b4e-937b-29cca3cbe168)

**Comment by tmas0** [comment]
Corregido.

Un saludo
