### ISSUE TITLE
Asistencia: Listados de estudiantes truncados, no aparacen todos los enrolados

### ISSUE THREAD

**Issue by moodleulpgc** [UNIMOODLE/moodle-mod_hybridteaching#116]
Hay dos páginas que muestran listados de estudiantes, incluyendo calificaciones. Si hay  calificaciones, en esos listados deben aparecer TODOS los estudiantes enrolados (salvo filtrado por grupo u otra condición): 

Asistencia de estudiantes (todas las sesiones) 
```
hybridteaching/attendance.php?id=21209&view=extendedstudentatt
```
Asistencia a sesiones, listado de una sesión
```
hybridteaching/attendance.php?id=21209&sessionid=25&view=extendedsessionatt
```
 Además, debe ser posible para el profesor cambiar la asistencia, o bien  dar por válida una asistencia insuficiente, o marcar tarío, o declararlo exento a un estudiante. Aunque NO hubiera participado en absoluto.  Esto es esencial en la 2ª pagina (sessionid not empty). No tanto en la primera, 

El problema es que solo se presenta un listado de los estudiantes para los que existe una entrada en hybridteaching_attendance que parece que NO son todos los matriculados.  Siendo esto así, es imposible para el profesor dar por asistido a estudiantes que NO aparecen en la tabla, o declararlos exentos. **Eso es un error, impide una función deseada**. 

El problema reside en la propia estructura de attendance_render.php   print_attendance_table(), que NO es sql sino que depende de un listado de filas obtenido separademente. Se traza hasta  attendance_controller load_attendance()

```
            $sql = 'SELECT ha.id, ha.sessionid, hs.name, hs.starttime, hs.duration, hs.typevc, ha.visible, ha.grade,
                            ha.userid, CASE WHEN ha.connectiontime = 0 THEN -1 ELSE ha.type END as type, ha.status,
                            ha.connectiontime, (hs.starttime + hs.duration) endtime, ha.exempt, u.lastname, u.username
                      FROM {hybridteaching_attendance} ha
                      JOIN {hybridteaching_session} hs on (ha.sessionid = hs.id)
                      JOIN {user} u on (u.id = ha.userid)
                     WHERE ha.hybridteachingid = :hybridteachingid ' . $where . ' ' . $fname . $lname . '
                  GROUP BY ha.id,
```
Tal como está planteada si NO hay registro en hybridteaching_attendance, NO aparece un  ítem en el retorno de esa consulta. 

La query debe plantearse al revés, y como una LEFT JOIN 
```
       FROM {user} u
LEFT JOIN {hybridteaching_attendance} ha ON  u.id = ha.userid 
```
Esto SI trae a todos los usuarios, y sis hay datos de asistencia, esos datos. Otra parte de la query delimita qué usuarios deben obtenerse (curso, grupo, enrol). 

Insisto, para estos listados inspirarse en la gradingtable de  mod_assign
Allí, precisamente,  se plantea la búsqueda de usuarios como 

```
        $from = '{user} u
                         LEFT JOIN {assign_submission} s
                                ON u.id = s.userid
                               AND s.assignment = :assignmentid1
                               AND s.latest = 1 ';

        // For group assignments, there can be a grade with no submission.
        $from .= ' LEFT JOIN {assign_grades} g
                            ON g.assignment = :assignmentid2 
```
Y luego otro JOIN con enrol  y user_enrolment (y en su cado groups_members) delimita los usuarios matriculados en el curso y grupo indicado.

**Comment by tmas0** [comment]
Buenas,

Confirmado.

Un saludo
