### ISSUE TITLE
Grabaciones en BBB: no aparece nada, ni grabación ni chat

### ISSUE THREAD

**Issue by moodleulpgc** [UNIMOODLE/moodle-mod_hybridteaching#120]
En otro issue ( #102) comentaba que NO podía realizar grabaciones, en general. En las últimas versiones SI que puedo. Tanto en teams como en BBB (en Zoom no he podido por licencias, pero Tmas indica que tampoco de pueden descargar)

Ahora SI puedo realizar grabaciones en BBB. Eso se ha solucionado. Bien! 
Como muestra esta imagen, se dispara una sesión BBB con la grabación activa y con cosas en el chat público.  
![Screenshot_20240314_170031](https://github.com/UNIMOODLE/moodle-mod_hybridteaching/assets/1895434/f5e9bc20-7c1e-46e4-af6e-6ead5ff71c04)

Pero  cuando se termina la sesión y se vuelve, o incluso al día siguente, a la página de sesiones realizadas NO hay indicación alguna de que esa sesión BBB tuviera una grabación o chat. 
![Screenshot_20240314_180514](https://github.com/UNIMOODLE/moodle-mod_hybridteaching/assets/1895434/3b5cb7ff-b4df-4a86-b44c-4dc24a0bed7d)

lo que vemos es que la task  `hybridteachvc_bbb\task\downloadrecords` nunca encuentra nada. Y eso es **falso, incorrecto**. 
```
Execute scheduled task: Descargar grabaciones BigBlueButton (hybridteachvc_bbb\task\downloadrecords)
... started 18:01:21. Current memory use 14.9 MB.
... used 1 dbqueries
... used 0.023545026779175 seconds
Scheduled task complete: Descargar grabaciones BigBlueButton (hybridteachvc_bbb\task\downloadrecords)
```
En una sesión normal BBB del mod_bigbluebuttonbn, aparecería en la sección de Grabaciones un botón "Presentación" para visualizar el stream. Eso mismo, al menos, necesitamos aquí. Y acecder, separadamente, al contenido del texto del chat público.  Si los estudiantes pueden "descargar grabaciones" debería haber un enlace al archivo .mp4 de ese stream

**Comment by tmas0** [comment]
Buenas @mcalvoisyccom,

Nos deja grabar y escribir perfectamente en el chat, tanto estudiantes como profesores.
Un vez ejecutado el cron de bajada de BBB, sin que de errores, y ejecutando el de OneDrive que es el storage que tenemos por defecto, no salen las grabaciones en la tabla. Tampoco sale el chat.

![Selecció_1270](https://github.com/UNIMOODLE/moodle-mod_hybridteaching/assets/970116/e4ce41a3-4e37-4ffa-a374-b7874e5c652c)

+ info: en la tabla hybridteaching_session el campo storagereference está a -1. Pero entiendo que es normal porque BBB no permite descargar.

Un saludo

**Comment by mcalvoisyccom** [comment]
Hola Toni
en el caso de BBB, que no es posible descargar, se controla el campo processedrecording:

Los valores son: processedrecording:  -1: no downloaded from vc yet (ready for download), 0: downloaded from vc, -2: no recording, positive number: activity id storage.

Antes de ejecutar el cron de BBB, processedrecording debe ser -1.
Una vez ejecutado el cron de descarga de BBB, los valores son: processedrecording=0, y storagereference=-1
En la tabla hybridteachvc_bbb, debe contener un meetingid y un recordingid.

Comprueba los valores que hay en las tablas. En caso de que no haya alguno, envíanos los valores de las tablas hybridteaching-session y hybridteachvc_bbb y vemos lo que ocurre.

Un saludo,
Marian Calvo.

**Comment by tmas0** [comment]
Buenas @mcalvoisyccom,

Tengo exactamente lo que comentas, tanto en una tabla como en la otra, pero sigo experimentando el mismo problema. No se ven los vídeos.

**Comment by mcalvoisyccom** [comment]
Hola @tmas0 ,
parece que depende de la versión de instalación de BBB: la api BBB devuelve la grabación en un campo distinto en función de la versión utilizada en BBB. En la próxima subida del plugin lo veréis ya solventado.

**Comment by mcalvoisyccom** [comment]
Solventado con la última versión añadida.

**Comment by tmas0** [comment]
Ya devuelve la grabación, pero no devuelve el chat.

**Comment by mcalvoisyccom** [comment]
@tmas0 , BBB no devuelve el chat por independiente, no hay opciones por la API. Se puede ver el chat desde la misma grabación, ya que abre la grabación junto con la ventana de chat.
