### ISSUE TITLE
Mejorar el README de onedrive (store)

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/moodle-mod_hybridteaching#125]
Buenas,

Estamos intentando configurar el storage de OneDrive, pero con la información que facilitáis en https://github.com/UNIMOODLE/moodle-mod_hybridteaching/blob/master/store/onedrive/Readme.md no lo podemos configurar.

Por favor, ¿podéis mejorarla a fin de que quede claro dónde hay que ir a configurar, y en que apartados se deben establecer los privilegios descritos?

Por ejemplo, cuando ponéis "AZURE CONFIG:

** Crear en azure una nueva App, o bien se permite utilizar la misma app que con el subplugin teams de hybridteaching." dónde hay que ir para ello, una URL de referencia ayudaría a aclararlo.
O cuando ponéis: "En la configuración de AZURE:", URL o path de referencia, alguna captura de pantalla para que quede más claro.

Muchas gracias

**Comment by tmas0** [comment]
Buenas @mcalvoisyccom,

A ver, tener una guia de ayuda, con una información completa, ayudará a mitigar muchas dudas durante el proceso de instalación y configuración del plugin.

Consideramos que se debe mejorar la explicación dada en https://github.com/UNIMOODLE/moodle-mod_hybridteaching/blob/master/store/onedrive/Readme.md

Un saludo

**Comment by mcalvoisyccom** [comment]
Solventado con la última versión añadida.

**Comment by tmas0** [comment]
Buenas @mcalvoisyccom,

Observo faltas de ortografía en dicha documentación. P.e:
>  Una gúí está disponible aquí

Un saludo

**Comment by tmas0** [comment]
Otro:
> El registro de la aplicación establece una relación de confianza entre la aplicació y la plataforma

**Comment by mcalvoisyccom** [comment]
@tmas0 ,
gracias, realmente no son faltas de ortografía, sino que falta alguna letra olvidada en el texto. No es algo bloqueante. Lo modificamos a la próxima.

**Comment by tmas0** [comment]
Sigue habiendo algún que otro fallo, pero doy por cerrado este tema.
