### ISSUE TITLE
HTML con sintaxis errónea en plantilla

### ISSUE THREAD

**Issue by LuksAO** [UNIMOODLE/moodle-mod_hybridteaching#129]
Moodle version: 4.1.10+ (Build: 20240530)
Usando el entorno de docker: https://github.com/moodlehq/moodle-docker

Cuando entro a la página de view.php de un mod se ve así:

![image](https://github.com/UNIMOODLE/moodle-mod_hybridteaching/assets/43584301/e7229b6e-6687-490a-ba7c-eddd0e809647)

(El footer coge todo el espacio).

En la plantilla mod/hybridteaching/templates/view_page_zone_access.mustache hay algún elemento HTML erróneo, hay 9 tags de divs abiertas (`<div`) y 11 cerradas (`</div>`).

Eliminando las 2 últimas etiquetas </div> se soluciona en mi entorno.

**Comment by mcalvoisyccom** [comment]
Hola, @LuksAO @juacas ,
cierto, hemos modificado los divs de la plantilla para arreglar la vista.
