### ISSUE TITLE
Warning single_button deprecation

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_hybridteaching#130]
Al crear una instancia nueva sale este warning:

The boolean $primary is deprecated and replaced by $type, use single_button::BUTTON_PRIMARY or self::BUTTON_SECONDARY instead
line 917 of /lib/outputcomponents.php: call to debugging()
line 397 of /mod/hybridteaching/mod_form.php: call to single_button->__construct()
line 137 of /mod/hybridteaching/mod_form.php: call to mod_hybridteaching_mod_form->hybridteaching_mform_insert_roles_access_mapping()
line 217 of /lib/formslib.php: call to mod_hybridteaching_mod_form->definition()
line 127 of /course/moodleform_mod.php: call to moodleform->__construct()
line 161 of /course/modedit.php: call to moodleform_mod->__construct()

**Comment by agonzalezisyc** [comment]
Hola,

¿Que versión de moodle estas utilizando?

**Comment by juacas** [comment]
Moodle 4.3

La siguiente release LTS será la 4.5 y saldrá en octubre.

 

De: agonzalezisyc ***@***.***> 
Enviado el: miércoles, 7 de agosto de 2024 9:29
Para: UNIMOODLE/moodle-mod_hybridteaching ***@***.***>
CC: Juan Pablo de Castro ***@***.***>; Author ***@***.***>
Asunto: Re: [UNIMOODLE/moodle-mod_hybridteaching] Warning single_button deprecation (Issue #130)

 

Hola,

¿Que versión de moodle estas utilizando?

**Comment by mcalvoisyccom** [comment]
Solventado con la última versión añadida.
