### ISSUE TITLE
Invalid event function

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_hybridteaching#131]
Invalid event functions defined in \mod_hybridteaching\event\attendance_viewed
line 275 of /lib/classes/event/base.php: call to debugging()
line 376 of /mod/hybridteaching/classes/local/attendance_table.php: call to core\event\base::create()
line 96 of /mod/hybridteaching/attendance.php: call to mod_hybridteaching\local\attendance_table->print_attendance_table()

**Comment by mcalvoisyccom** [comment]
Solventado con la última versión añadida.
