### ISSUE TITLE
SQL query with unnedeed JOIN.

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_hybridteaching#134]
https://github.com/UNIMOODLE/moodle-mod_hybridteaching/blob/6df1b00d5e8ebc9351f8a1249053b367e23f91ba/classes/controller/sessions_controller.php#L945

Don't use the JOIN with course_modules.
Also, the signature of the method says it returns "sessions" so the return time should have full records from database.
IMHO it should be:

```php
        $sql = 'SELECT hts.*
                  FROM {hybridteaching_session} hts       
                 WHERE hts.hybridteachingid = ?
                   AND hts.starttime < ?
                   AND hts.starttime + hts.duration > ?';
```

**Comment by mcalvoisyccom** [comment]
Solventado con la última versión añadida.

**Comment by tmas0** [comment]
Comprobado.
