### ISSUE TITLE
Legacy functions deprecated in event objects

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_hybridteaching#136]
Invalid event functions defined in \mod_hybridteaching\event\attendance_viewed
line 275 of /lib/classes/event/base.php: call to debugging()
line 376 of /mod/hybridteaching/classes/local/attendance_table.php: call to core\event\base::create()
line 96 of /mod/hybridteaching/attendance.php: call to mod_hybridteaching\local\attendance_table->print_attendance_table()

Call to legacy_log are deprecated.

**Comment by juacas** [comment]
Fixed in 00480acc35f72f34d5364c8d8c2b107372a17533
Please review and mark as solved.

**Comment by mcalvoisyccom** [comment]
Solventado con la última versión añadida.

**Comment by tmas0** [comment]
Comprobado.
