### ISSUE TITLE
Error con clase no encontrada, y también constante

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/moodle-mod_hybridteaching#147]
Buenas,

Tras la última subida, en mod_form.php:400 se ha puesto
```
get_config('moodle', 'version') > '2022112810' ? single_button::BUTTON_PRIMARY : false,
```

Hay un error ahí:
- O bien se añade un \
- O bien se establece el use single_button correspondiente al inicio del fichero.

El error es:
```
Excepción - Undefined constant single_button::BUTTON_PRIMARY
```
Entonces, revisando, en Moodle 4.1.13 no existe esa constante. Por tanto, revisar ese aspecto.

Un saludo

**Comment by agonzalezisyc** [comment]
Hola Toni,

Hemos subido una correción, ¿puedes comprobar que funciona?

Un saludo.

**Comment by tmas0** [comment]
Perfecto, si, arreglado.

Muchas gracias!
