### ISSUE TITLE
Diversos fallos al generar una actividad con inicio de sesión programado

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/moodle-mod_hybridteaching#148]
Buenas,

Generamos una actividad con inicio de sesión fijada a un momento determinado:
![Selecció_1326](https://github.com/user-attachments/assets/e7fb03eb-11fa-4cab-926d-ae71ac84f62a)

Vemos varios temas:
1. Siendo antes de la hora, sale el mensaje: "Inició el xxxx de xxx de xxx a las (hora del futuro). La captura de pantalla se hizo a las 9:21, y como se observa, el inicio está previsto a las 9:30. Entendemos que es un fallo en la descripción o estado. Entendemos que debería ser: "Iniciará..." ![Selecció_1325](https://github.com/user-attachments/assets/4360f8b0-23a8-4f32-a842-23fe5e4369b9)
2. En la captura anterior, salen los botones de Mostrar Contraseña y Finalizar sesión. ¿Como se puede finalizar una sesión programada a las 9:30 cuando eran las 9:21? Al pulsar sobre finalizar, da el error de que no se puede finalizar una sesión que no ha empezado (que está bien). Entonces, entendemos que ese botón no debería salir en ese momento temporal.

Un saludo

**Comment by mcalvoisyccom** [comment]
Solventado con la última versión añadida.

**Comment by tmas0** [comment]
Comprobado.
