### ISSUE TITLE
Warning al programar una sesión con duración máxima

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/moodle-mod_hybridteaching#149]
Buenas,

Al configurar una actividad con:
![Selecció_1327](https://github.com/user-attachments/assets/a8894961-ca89-4bed-9212-7196c593c938)

Tanto al profesor como a los estudiantes les sale el siguiente warning.
```
Warning: Attempt to read property "id" on bool in /server.de/moodle/mod/hybridteaching/view.php on line 259
```
Un saludo

PD: Le pongo etiqueta bug, pero no es un bug grave como tal, sino un arreglo menor.

**Comment by mcalvoisyccom** [comment]
Solventado con la última versión añadida.

**Comment by tmas0** [comment]
Comprobado.
