### ISSUE TITLE
No aparece el nombre y descripción de las sesiones

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_hybridteaching#151]
En las pantalla inicial, se muestra el título y descripción de la actividad, pero no el título y descripción de la sesión activa.

Dado que esta pantalla está dedicada a interactuar con al SESIÓN es necesario que se identifique correctamente la sesión en curso. Esto debe incluir Título, Descriptción. En la captura adjunta el texto que aparece es el de la actividad general.

![image](https://github.com/user-attachments/assets/409a9bef-eef7-4883-b976-1f567f94e13d)

**Comment by tmas0** [comment]
Comprobado.
