### ISSUE TITLE
No encuentro caso de uso 5 requisito S3a

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_hybridteaching#154]
2.2.5	Caso de uso 5: Clase Híbrida para un tema/sesión específica
•	Como Profesor quiero poder añadir al curso una actividad que represente una única sesión de videoconferencia sin restricciones temporales, para necesidades docentes específicas (tratar un tema concreto, un tipo de actividad diferenciada). Por ejemplo, para soporte a Prácticas de Laboratorio, o a grupos de trabajo tutelado. 
Quiero que estas sesiones estén disponibles permanentemente (sin fechas), o en una agenda no confundida con las de otras sesiones de clase, con una forma de configuración simple y directa.  

No encuentro la forma de hacerlo.

**Comment by mcalvoisyccom** [comment]
Hola @juacas ,
esto está ya contemplado y resuelto.

Es la opción "Sesión única" y "Sesiones recurrentes" de la pestaña de ajustes de "Temporalización de sesiones".
![image](https://github.com/user-attachments/assets/b25a0953-b1d7-4706-ab13-9cb7ad958469)

La opción Sesión única crea una única sesión, puede ser para un momento determinado, o sin asignar momento temporal.
Sesiones recurrentes crea sesiones desde la vista principal, de manera simple para el profesor, para utilizarlo en cualquier momento, sin fecha establecida.

**Comment by mcalvoisyccom** [comment]
Hola @juacas ,
sí, disculpa, la imagen que añadí antes es de una versión más antigua. Se modificó posteriormente a checkboxes para poder utilizar distintos elementos en una sola vez, según vuestras indicaciones. La imagen correcta es la que envías. Así se puede utilizar conjuntamente la opción de fecha/hora junto con reutilización de recurso interno.
Programación de sesiones: checkbox. Si se utiliza, se podrán programar varias sesiones en una misma actividad.
Reutilizar recurso interno: utiliza el mismo recurso para la reunión.
Habilitar inicio de sesión: marcando crea una sola sesión en un momento determinado, si no hay programación de sesiones marcado. Si no se utiliza inicio de sesión, se puede crear la sesión en el momento en que se necesite, sin restricción temporal.
