### ISSUE TITLE
Con la última actualización, al estar en marcha una sesión, los estudiantes no pueden acceder a la VC (comprobado usando Teams y BBB)

### ISSUE THREAD

**Issue by tmas0** [UNIMOODLE/moodle-mod_hybridteaching#156]
Buenas @mcalvoisyccom,

Tras la última actualización vemos que los estudiantes no se les permite acceder a la sala de VC (comprobado en Teams y BBB). Para entendernos, no les sale el botón verde de unirse. ¿Lo podéis revisar?

![Selecció_1328](https://github.com/user-attachments/assets/b9b47e40-357a-4fc3-ba63-bf4c10da6014)

Un saludo

**Comment by mcalvoisyccom** [comment]
Hola @tmas0 ,
¿puedes indicarnos como has configurado la pestaña Temporalización de sesiones ?

**Comment by tmas0** [comment]
Buenas @mcalvoisyccom,

Aquí va:
- con BBB:
![Selecció_1332](https://github.com/user-attachments/assets/d5d85645-218f-4b35-bbe5-ff5205f2e313)

- con Teams:
![Selecció_1333](https://github.com/user-attachments/assets/5eafd2fd-0fbe-4b9b-93c4-343a72b0233a)

Un saludo

**Comment by mcalvoisyccom** [comment]
Solventado con la última versión añadida.

**Comment by tmas0** [comment]
Comprobado.
