### ISSUE TITLE
Menús de actividad desordenados en hybridteaching_extend_settings_navigation.

### ISSUE THREAD

**Issue by juacas** [UNIMOODLE/moodle-mod_hybridteaching#157]
Cuando un usuario tiene capabilities superiores a los de el rol "legacy teacher" los menús de la actividad aparecen separados y desordenados.

![image](https://github.com/user-attachments/assets/653d5aa4-91fc-4173-8767-b8ceaea4bdd4)

Deben aparecer agrupados y al principio de la lista de opciones. Como está ahora, es un caos. Para ellos hay que especificar explícitamente el orden de los menús en la función add_node..

En https://github.com/UNIMOODLE/moodle-mod_hybridteaching/blob/1cfb293415322c7e814e8330b3744c369c58730f/lib.php#L500 la implementación no es eficaz. En lugar de generar un array de elementos, sería mejor llamar dentro de cada if a la función de construcción del menú con las opciones correspondientes, prestando atención especialmente a "beforekey" que permite asegurar un orden.  La generación de un array intermedio para inmediatamente luego iterar, además perdiendo información de contexto, no tiene sentido en este caso de uso.

Una solución que funciona en mi prueba es usar beforekey:"modedit" :
```php
$hybridteachingnode->add_node(childnode: navigation_node::create($title], $url, navigation_node::TYPE_SETTING), beforekey:"modedit");
```

![image](https://github.com/user-attachments/assets/c6532ee5-8daa-437c-9407-dd7298eb7121)

**Comment by mcalvoisyccom** [comment]
Solventado con la última versión añadida.

**Comment by tmas0** [comment]
Comprobado.
