### ISSUE TITLE
Config mod_form: Inicio de sesión y antelación / esperar al moderador

### ISSUE THREAD

**Issue by moodleulpgc** [UNIMOODLE/moodle-mod_hybridteaching#98]
En parámetro de antelación de entrada debe controlar cuándo se presenta el botón para unirse a la sesión. 
Debe afectar a todos los roles, profesores y estudiantes. Cuando hay una fecha definida para inicio de la próxima sesión (bien en configuración de instancia o en sesión programada)
La opción "esperar al moderador" debe afectar al resto que NO son moderadores. No s epresenta el botón, incluso estando dentro del periodo de antelación de entrada, si no ha entrado previamenete el moderador. 
Estando como estudiante, un contador JS debe chequear periódicamente (cada 10-20 s) si ya ha entrado el moderador. 

En el pantallazo inferior, hay un inicio de sesión configurado en la propia instancia. Pero el parámetro  antelación de entrada está deshabilidado, freezed. Y no depende de esperar al moderador, ocurre en ambos casos. 

![Screenshot 2024-02-12 at 10-46-05 Editando Docencia híbrida moodle4unimoodle](https://github.com/UNIMOODLE/moodle-mod_hybridteaching/assets/1895434/ee986b45-0546-4806-b7d0-3c6a8baa56c2)

**Comment by tmas0** [comment]
Confirmamos que funciona en general, pero vemos peculiaridades. Al ser específico, abriremos ticket para cada uno de ellos, por así centrar los esfuerzos de la mejor manera posible.
